# Generated by Django 4.2.16 on 2024-11-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0002_remove_dokumen_user_remove_organisasi_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='author',
        ),
        migrations.RemoveField(
            model_name='organisasi',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pemohon',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pengurus',
            name='author',
        ),
    ]
