# Generated by Django 4.2.16 on 2024-11-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0003_remove_dokumen_author_remove_organisasi_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
