# Generated by Django 4.2.16 on 2024-11-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0004_alter_register_register'),
    ]
    
    operations = [
    migrations.AddField(
        model_name='register',
        name='created_at',
        field=models.DateTimeField(auto_now_add=True),
    ),
]

