# Generated by Django 4.2.16 on 2024-11-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0007_alter_dokumen_id_alter_organisasi_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemohon',
            name='surat_permohonan_skt',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/surat_permohonan/'),
        ),
    ]
