# Generated by Django 4.2.16 on 2024-11-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0008_alter_pemohon_surat_permohonan_skt'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='dokumen/logo/'),
        ),
    ]
