# Generated by Django 4.2.16 on 2024-11-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0009_register_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='logo',
            field=models.ImageField(null=True, upload_to='dokumen/logo/'),
        ),
    ]
