# Generated by Django 4.2.16 on 2024-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0010_alter_register_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengurus',
            name='agama_bendahara',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pengurus',
            name='agama_ketua',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pengurus',
            name='agama_pendiri',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pengurus',
            name='agama_sekretaris',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=50),
        ),
    ]
