# Generated by Django 4.2.16 on 2024-11-10 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0011_alter_pengurus_agama_bendahara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='tanggal_lahir_bendahara',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='pengurus',
            name='tanggal_lahir_ketua',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='pengurus',
            name='tanggal_lahir_pendiri',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengurus',
            name='tanggal_lahir_sekretaris',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
