# Generated by Django 4.2.16 on 2024-11-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0012_pengurus_tanggal_lahir_bendahara_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumen',
            old_name='npwp',
            new_name='npwp_pengurus',
        ),
    ]
