# Generated by Django 4.2.16 on 2024-11-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0013_rename_npwp_dokumen_npwp_pengurus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='surat_rekomendasi_1',
        ),
        migrations.RemoveField(
            model_name='dokumen',
            name='surat_rekomendasi_2',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='surat_rekomendasi_dua',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/', verbose_name='Surat Rekomendasi Dua'),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='surat_rekomendasi_satu',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/', verbose_name='Surat Rekomendasi Satu'),
        ),
    ]
