# Generated by Django 4.2.16 on 2024-11-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0014_remove_dokumen_surat_rekomendasi_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemohon',
            name='surat_permohonan_skt',
            field=models.FileField(default=1, upload_to='dokumen/surat_permohonan/'),
            preserve_default=False,
        ),
    ]
