# Generated by Django 4.2.16 on 2024-11-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0015_alter_pemohon_surat_permohonan_skt'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
