# Generated by Django 4.2.16 on 2024-11-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0017_remove_register_is_completed_register_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='status',
        ),
        migrations.AddField(
            model_name='register',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
