# Generated by Django 4.2.16 on 2024-11-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0020_remove_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
