# Generated by Django 4.2.16 on 2024-11-15 12:41

from django.db import migrations, models
import modelform.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0021_register_is_verified_register_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='logo',
            field=models.ImageField(null=True, upload_to=modelform.image_utils.logo),
        ),
    ]
