# Generated by Django 4.2.16 on 2024-11-15 12:51

from django.db import migrations, models
import modelform.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0022_alter_register_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='ad_art',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='AD/ART'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='akta_notaris',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Akta Notaris'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='biodata_pengurus',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Biodata Pengurus'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='foto_kantor',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Foto Kantor/Sekretariat'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='foto_pengurus',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Foto Pengurus'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='ktp_pengurus',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='KTP Pengurus'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='npwp_pengurus',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='NPWP'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='program_kerja',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Program Kerja'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='struktur_organisasi',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Struktur Organisasi'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='surat_domisili',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Surat Keterangan Domisili Ormas'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='surat_kepemilikan_gedung',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Surat Kepemilikan/Kontrak Gedung'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='surat_pernyataan_hak_paten',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Surat Pernyataan Hak Paten'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='surat_pernyataan_kesanggupan',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Surat Pernyataan Kesanggupan Melaporkan Kegiatan'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='surat_pernyataan_pejabat',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Surat Pernyataan Pejabat'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='surat_rekomendasi_dua',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Surat Rekomendasi Dua'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='surat_rekomendasi_satu',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Surat Rekomendasi Satu'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='surat_tidak_sengketa',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Surat Keterangan Tidak Dalam Sengketa'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='surat_tidak_terkait_politik',
            field=models.FileField(blank=True, null=True, upload_to=modelform.image_utils.dokumen, verbose_name='Surat Pernyataan Tidak Terkait Partai Politik'),
        ),
        migrations.AlterField(
            model_name='organisasi',
            name='bendera',
            field=models.ImageField(blank=True, null=True, upload_to=modelform.image_utils.logo),
        ),
        migrations.AlterField(
            model_name='organisasi',
            name='lambang_logo',
            field=models.ImageField(blank=True, null=True, upload_to=modelform.image_utils.logo),
        ),
        migrations.AlterField(
            model_name='pemohon',
            name='surat_permohonan_skt',
            field=models.FileField(upload_to=modelform.image_utils.surat_permohonan),
        ),
    ]
