# Generated by Django 4.2.16 on 2024-11-15 12:56

from django.db import migrations, models
import modelform.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0023_alter_dokumen_ad_art_alter_dokumen_akta_notaris_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='logo',
            field=models.ImageField(null=True, upload_to=modelform.image_utils.logo, validators=[modelform.image_utils.validate_file_size]),
        ),
    ]
